input.form-input {
    width: 100%;
    outline: none;
    border: none;
    height: 2rem;
    font-size: 16px;
    margin-bottom: 1px;
    border-bottom: 3px solid lightgray;
    transition: border ease-in 0.3s;
}

input.form-input:hover {
    border-bottom: 3px solid coral;
}

input.form-input:focus {
    border-bottom: 3px solid cornflowerblue;
}

.formGroup{
    height: 3rem;
}

nav ul {
    padding: 0;
    margin: 0;
    list-style: none;
    position: relative;
}

nav ul li {
    display: inline-block;
    background-color: whitesmoke;
}

nav a {
    display: block;
    padding: 0 10px;
    color: #4c4b57;
    font-size: 20px;
    line-height: 60px;
    text-decoration: none;
}

nav a:hover {
    background-color: #4c4b57;
    color: whitesmoke;
}

/* Hide Dropdowns by Default */
nav ul ul {
    display: none;
    position: absolute;
    top: 60px;
    /* the height of the main nav */
}

/* Display Dropdowns on Hover */
nav ul li:hover>ul {
    display: inherit;
}

/* Fisrt Tier Dropdown */
nav ul ul li {
    width: 170px;
    float: none;
    display: list-item;
    position: relative;
    z-index: 999;
}

/* Second, Third and more Tiers	*/
nav ul ul ul li {
    position: relative;
    top: -60px;
    left: 170px;
    z-index: 999;
}


/* Change this in order to change the Dropdown symbol */
li>a:after {
    content: '';
}

li>a:only-child:after {
    content: '';
}

nav {
    z-index: 999;
}

.cursors {
    cursor: pointer;
}